name: CICD pipeline
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-test-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: test with maven
        run: mvn clean test

      - name: Upload code coverage as artifact
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        uses: actions/upload-artifact@v2
        with:
          name: code coverage
          path: target/site/jacoco

      - name: build project
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        run: mvn clean package

      - name: Upload WAR file as artifact
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        uses: actions/upload-artifact@v2
        with:
          name: WAR file
          path: target/restapiweb.war

      - name: Create Github issue on failure
        if: failure()
        uses: ManojCSE17/open-issue@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Build failed on ${{github.event_name}} to the ${{ github.ref_name }}"
          assignees: |
            ManojCSE17
